#!/bin/python
# Antispam filter - project for BIS course at FIT BUT
# Author: Martin Krajnak
import sys
from os import path

# eml parser and deps
from eml_parser import eml_parser
import json # TODO delete, for debugging only
import datetime
import email.message

# Required for json printing
def json_serial(obj):
    if isinstance(obj, datetime.datetime):
        serial = obj.isoformat()
        return serial


def help():
    print("Usage: antispam [<file1> <file2> ...]")


def check_args(args):
    if len(args) == 0:
        help()


def spam_print(email, reason):
    print(email,"- SPAM -", reason)


def ok_print(email):
    print(email,"- OK")


def check_spam(email, content):
    if 'sex' in content:
        spam_print(email, 'Contains: sex')
    else:
        ok_print(email)

'''
Open mail, parse eml, check if body contains message,
@return message
'''
def get_message(email):
    with open(email, 'rb') as mail:
        content = mail.read()
        parsed_content = eml_parser.decode_email_b(content, include_raw_body=True)
        if 'body' in parsed_content.keys() and parsed_content['body'] != []:
            return parsed_content['body'][0]['content']
        else:
            import email

            return ''



'''
Main
'''
emails = sys.argv[1:]
check_args(emails)

for email in emails:
    try:
        msg = get_message(email)
        print(msg)
    except Exception as e:
        print(email,"- FAIL - failed to open email file")
        continue
