#!/bin/python
# Antispam filter - project for BIS course at FIT BUT
# Author: Martin Krajnak
import sys
from os import path

# eml parser and deps
from eml_parser import eml_parser
import json # TODO delete, for debugging only
import datetime

# Required for json printing
def json_serial(obj):
    if isinstance(obj, datetime.datetime):
        serial = obj.isoformat()
        return serial


def help():
    print("Usage: antispam [<file1> <file2> ...]")


def check_args(args):
    if len(args) == 0:
        help()


def spam_print(email, reason):
    print(email,"- SPAM -", reason)


def ok_print(email):
    print(email,"- OK")


def check_spam(email, content):
    if 'sex' in content:
        spam_print(email, 'Contains: sex')
    else:
        ok_print(email)


emails = sys.argv[1:]
check_args(emails)

for email in emails:
    try:
        with open(email, 'rb') as mail:
            content = mail.read()
            parsed_content = eml_parser.decode_email_b(content)
            print(json.dumps(parsed_content, default=json_serial))
            import ipdb; ipdb.set_trace()
            check_spam(email,content)
    except Exception as e:
        print(email,"- FAIL - failed to open email file")
        continue
